IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Help()
		Attack(NearestEnemyOf(Myself))
END

IF
	AttackedBy([PC],DEFAULT)
THEN
	RESPONSE #100
		Help()
		Attack(LastAttackerOf(Myself))
END

IF
	Help([0.0.SPIDER])
THEN
	RESPONSE #100
		Attack(LastAttackerOf(LastHelp))
END

IF
	True()
THEN
	RESPONSE #100
		SetSequence(SEQ_ATTACK)
END

