IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	HPPercentLT("BONE_3_1",75)
	!StateCheck("BONE_3_1",STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SpellRES("IDIN997","BONE_3_1") //INNATE_SHADOW_PACT
		Wait(2)
		//Continue()
END

IF
	HPPercentLT("BONE_3_2",75)
	!StateCheck("BONE_3_2",STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		SpellRES("IDIN997","BONE_3_2") //INNATE_SHADOW_PACT
		Wait(2)
		//Continue()
END

