IF
	True()
THEN
	RESPONSE #100
		CutSceneId("SEERTALK")
		Activate("SEERTALK")
		SetGlobal("IwIHidden","LOCALS",0)
		StartCutSceneMode()
		MultiPlayerSync()
		ClearAllActions()
		StartCutScene("BCTNTFC3")
		Wait(1)
		SetGlobal("BC_CUTSCENE","GLOBAL",18)
		Explore()
		UnhideGUI()
		//ResetJoinRequests()
		MultiPlayerSync()
		EndCutSceneMode()
		//Kill("SEER")  // Провидица
		ActionOverride("SEER",Kill(Myself))
		DestroySelf()
END

