IF
	Allegiance(Myself,ENEMY)
	NumTimesTalkedTo(0)
THEN
	RESPONSE #100
		SetNumTimesTalkedTo(1)
		Continue()
END

IF
	!NumTimesTalkedTo(0)
THEN
	RESPONSE #100
		ChangeAIScript("D4ELDG",GENERAL)
END

IF
	NumTimesTalkedTo(0)
	See([PC])
	!Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_REALLY_DEAD)
THEN
	RESPONSE #100
		StartCutSceneMode()
		ClearAllActions()
		MultiPlayerSync()
		ApplySpellRES("BDCUTSPY",Myself)
		StartDialogNoSet([PC])
END

