IF
	True()
THEN
	RESPONSE #100
		CutSceneId("EVERARD")
		StartCutSceneMode()
		ClearAllActions()
		MultiPlayerSync()
		HideGUI()
		MultiPlayerSync()
		MoveViewPoint([603.414],VERY_FAST)
		ActionOverride("POQUELIN",ForceSpellRES("IDPR608","EVERARD"))
		StartCutScene("EECRNATK")
		MoveToPoint([603.414])
		ActionOverride("POQUELIN",FaceObject("EVERARD"))
		MoveToPoint([603.414])
		ActionOverride("POQUELIN",FaceObject("EVERARD"))
		MoveToPoint([603.414])
		StartCutScene("EEENDCT4")
END

