IF
	Entered([PC])
THEN
	RESPONSE #100
		DisplayString(Myself,14381)  // Сработала ловушка
		ReallyForceSpellRES("idwi019",LastTrigger) //TRAP_DEATH_FOG)  // SPWI019.SPL (Смертельный Туман)
		Wait(2)
END

IF
	Opened([PC])
THEN
	RESPONSE #100
		DisplayString(Myself,14381)  // Сработала ловушка
		ReallyForceSpellRES("idwi019",LastTrigger) //TRAP_DEATH_FOG)  // SPWI019.SPL (Смертельный Туман)
		Wait(2)
END

