IF
	!BitCheck("CREATURE_STATE_VAR","LOCALS",1)
THEN
	RESPONSE #100
		BitSet("CREATURE_STATE_VAR","LOCALS",1)
		SetGlobal("IwIHidden","LOCALS",1)
		Deactivate(Myself)
		//SetGlobal("IwIHidden","LOCALS",1)
		//Continue()
END

IF
	!BitCheck("AREA_GROUP_VAR","MYAREA",1)
THEN
	RESPONSE #100
		NoAction()
END

IF
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
		Continue()
END

IF
	!IsActive(Myself)
THEN
	RESPONSE #100
		Activate(Myself)
		SetGlobal("IwIHidden","LOCALS",0)
		Continue()
END

