IF
	Global("MARKETH_BADGE","GLOBAL",0)
	PartyHasItem("MARKETH")
THEN
	RESPONSE #100
		SetGlobal("MARKETH_BADGE","GLOBAL",1)
		AddXP2DA("ID1EX11A")
		DisplayStringNoName(Player1,@19561)
		Continue()
END

IF
	Global("MAP_GROUP_HOSTILE5","MYAREA",0)
	!Global("SPRITE_IS_DEADMARKETH","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("MAP_GROUP_HOSTILE5","MYAREA",1)
		Continue()
END

IF
	OnCreation()
THEN
	RESPONSE #100
		NoAction()
		Continue()
END

