IF
  Global("SaveSavedLoc","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("SaveSavedLoc","LOCALS",1)
    SaveObjectLocation("LOCALS","SavedLoc",Myself)
    Continue()
END

IF
	!Global("SAW_PC","LOCALS",0)
	ActionListEmpty()
	!See([PC])
THEN
  RESPONSE #100
    MoveToObject(Player1)
  RESPONSE #100
    NoAction()
END



IF
	ActionListEmpty()
	!NearSavedLocation(Myself,"LOCALSSavedLoc",0)
THEN
	RESPONSE #100
		RandomWalk()
		WaitRandom(0,0)
END

