IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		FaceObject("PURVIS")
END

IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player2)
		FaceObject("PURVIS")
END

IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player3)
		FaceObject("PURVIS")
END

IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player4)
		FaceObject("PURVIS")
END

IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player5)
		FaceObject("PURVIS")
END

IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player6)
		FaceObject("PURVIS")
END

