IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	!GlobalTimerNotExpired("IWD_Rest","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("IWD_Rest","LOCALS",EIGHT_HOURS)
		ApplySpell(Myself,RESTORE_FULL_HEALTH)
		Rest()
END

IF
	!BitCheck("CREATURE_STATE_VAR","LOCALS",256)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		BitSet("CREATURE_STATE_VAR","LOCALS",256)
		BitSet("AREA_VAR","MYAREA",32)
		DisplayStringHead(Myself,@11733)
		Continue()
END

IF
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	!StateCheck(Myself,STATE_REALLY_DEAD)
	HPPercentLT(Myself,60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_CURE_MEDIUM_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	See(NearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	See(SecondNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	See(ThirdNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	See(FourthNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	See(FifthNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	See(SixthNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	See(SeventhNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	See(EighthNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	See(NinthNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	See(TenthNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_MEDIUM_WOUNDS)
	See([ENEMY])
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_MEDIUM_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	!StateCheck(Myself,STATE_REALLY_DEAD)
	HPPercentLT(Myself,60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(Myself,CLERIC_CURE_LIGHT_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	See(NearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	See(SecondNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	See(ThirdNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	See(FourthNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	See(FifthNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	See(SixthNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	See(SeventhNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	See(EighthNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	See(NinthNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	See(TenthNearestMyGroupOfType)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
		Wait(2)
END

IF
	HaveSpell(CLERIC_CURE_LIGHT_WOUNDS)
	See([ENEMY])
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	HPPercentLT(LastSeenBy(Myself),60)
	Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Spell(LastSeenBy(Myself),CLERIC_CURE_LIGHT_WOUNDS)
		Wait(2)
END

IF
	See(NearestEnemyOf(Myself))
	Global("SPELL_PHASE","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",1)
		Spell(Myself,CLERIC_CLOAK_OF_FEAR)
		Wait(2)
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",1)
		Spell(LastSeenBy(Myself),CLERIC_MENTAL_DOMINATION)
		Wait(2)
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",1)
		Spell(Myself,CLERIC_DEFENSIVE_HARMONY)
		Wait(2)
END

IF
	See(NearestEnemyOf(Myself))
	Global("SPELL_PHASE","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",2)
		Spell(Myself,CLERIC_CHANT)
		Wait(2)
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",2)
		Spell(Myself,CLERIC_STRENGTH_OF_ONE)
		Wait(2)
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",2)
		Spell(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
		Wait(2)
END

IF
	See(NearestEnemyOf(Myself))
	Global("SPELL_PHASE","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",3)
		Spell(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
		Wait(2)
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",3)
		Spell(LastSeenBy(Myself),CLERIC_MISCAST_MAGIC)
		Wait(2)
END

IF
	See(NearestEnemyOf(Myself))
	Global("SPELL_PHASE","LOCALS",3)
THEN
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",4)
		Spell(LastSeenBy(Myself),CLERIC_SILENCE_15_FOOT)
		Wait(2)
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",4)
		Spell(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
		Wait(2)
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",4)
		Spell(LastSeenBy(Myself),CLERIC_CHANT)
		Wait(2)
END

IF
	See(NearestEnemyOf(Myself))
	Global("SPELL_PHASE","LOCALS",4)
THEN
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",5)
		Spell(LastSeenBy(Myself),CLERIC_ENTANGLE)
		Wait(2)
	RESPONSE #100
		SetGlobal("SPELL_PHASE","LOCALS",5)
		SpellRES("IDPR111",LastSeenBy(Myself))
		Wait(2)
END

IF
	Global("SPELL_PHASE","LOCALS",5)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),75)
END

IF
	AttackedBy(NearestEnemyOf(Myself),DEFAULT)
THEN
	RESPONSE #100
		FaceObject(LastAttackerOf(Myself))
		Continue()
END

IF
	!Allegiance(Myself,ENEMY)
	AttackedBy([GOODCUTOFF],DEFAULT)
THEN
	RESPONSE #100
		Enemy()
		Continue()
END

