IF
	StateCheck(Myself,STATE_PANIC)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	OR(3)
		See([0.0.ORC])
		See([0.0.MYCONID])
		See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		AttackReevaluate(LastSeenBy(Myself),75)
END

IF
	Help([0.0.ETTIN])
THEN
	RESPONSE #100
		MoveToObject(NearestEnemyOf(LastHelp(Myself)))
END

IF
	AttackedBy([ANYTHING],DEFAULT)
THEN
	RESPONSE #100
		Help()
		MoveToObject(LastAttackerOf(Myself))
END

