IF
	!Global("KILL_LICH_MINIONS","MYAREA",0)
THEN
	RESPONSE #100
		Kill(Myself)
END

IF
	!BitCheck("CREATURE_STATE_VAR","LOCALS",1)
THEN
	RESPONSE #100
		BitSet("CREATURE_STATE_VAR","LOCALS",1)
		IncrementGlobal("UD_LICH_SPAWN_CNT","MYAREA",1)
		Continue()
END

IF
	!Global("LICH_MINIONS_FOLLOW","MYAREA",0)
	!See(NearestEnemyOf(Myself))
	ActionListEmpty()
	!See([PC])
THEN
  RESPONSE #100
    MoveToObject(Player1)
END



